services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=project_scheduler_db
      - POSTGRES_PASSWORD=magic
    ports:
      - "5433:5432"
volumes:
  db_volume: