#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["ProjectScheduler.Api/ProjectScheduler.Api.csproj", "ProjectScheduler.Api/"]
COPY ["ProjectScheduler.Application/ProjectScheduler.Application.csproj", "ProjectScheduler.Application/"]
COPY ["ProjectScheduler.Domain/ProjectScheduler.Domain.csproj", "ProjectScheduler.Domain/"]
COPY ["ProjectScheduler.Infrastructure/ProjectScheduler.Infrastructure.csproj", "ProjectScheduler.Infrastructure/"]
RUN dotnet restore "ProjectScheduler/ProjectScheduler.Api/ProjectScheduler.Api.csproj"
COPY . .
WORKDIR "/src/ProjectScheduler.Api"
RUN dotnet build "ProjectScheduler.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProjectScheduler.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProjectScheduler.Api.dll"]